# Generated by Django 4.2.5 on 2023-10-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
